name: assignment-test
on: [push]
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:assignment1
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: setup python
            uses: actions/setup-python@v4
            with:
              python-version: 3.8.10
                
          - name: Run full test
            run: ./full-test.sh
